#pragma once

#include <functional>
#include "GL/freeglut.h"

namespace FreeGLUT {

	// Explicit linking
	void loadDLL();
	void unloadDLL();

	// Auto-generated
	using PFN_glutInit                       = std::function<decltype(::glutInit)>;
	using PFN_glutInitWindowPosition         = std::function<decltype(::glutInitWindowPosition)>;
	using PFN_glutInitWindowSize             = std::function<decltype(::glutInitWindowSize)>;
	using PFN_glutInitDisplayMode            = std::function<decltype(::glutInitDisplayMode)>;
	using PFN_glutInitDisplayString          = std::function<decltype(::glutInitDisplayString)>;
	using PFN_glutMainLoop                   = std::function<decltype(::glutMainLoop)>;
	using PFN_glutCreateWindow               = std::function<decltype(::glutCreateWindow)>;
	using PFN_glutCreateSubWindow            = std::function<decltype(::glutCreateSubWindow)>;
	using PFN_glutDestroyWindow              = std::function<decltype(::glutDestroyWindow)>;
	using PFN_glutSetWindow                  = std::function<decltype(::glutSetWindow)>;
	using PFN_glutGetWindow                  = std::function<decltype(::glutGetWindow)>;
	using PFN_glutSetWindowTitle             = std::function<decltype(::glutSetWindowTitle)>;
	using PFN_glutSetIconTitle               = std::function<decltype(::glutSetIconTitle)>;
	using PFN_glutReshapeWindow              = std::function<decltype(::glutReshapeWindow)>;
	using PFN_glutPositionWindow             = std::function<decltype(::glutPositionWindow)>;
	using PFN_glutShowWindow                 = std::function<decltype(::glutShowWindow)>;
	using PFN_glutHideWindow                 = std::function<decltype(::glutHideWindow)>;
	using PFN_glutIconifyWindow              = std::function<decltype(::glutIconifyWindow)>;
	using PFN_glutPushWindow                 = std::function<decltype(::glutPushWindow)>;
	using PFN_glutPopWindow                  = std::function<decltype(::glutPopWindow)>;
	using PFN_glutFullScreen                 = std::function<decltype(::glutFullScreen)>;
	using PFN_glutPostWindowRedisplay        = std::function<decltype(::glutPostWindowRedisplay)>;
	using PFN_glutPostRedisplay              = std::function<decltype(::glutPostRedisplay)>;
	using PFN_glutSwapBuffers                = std::function<decltype(::glutSwapBuffers)>;
	using PFN_glutWarpPointer                = std::function<decltype(::glutWarpPointer)>;
	using PFN_glutSetCursor                  = std::function<decltype(::glutSetCursor)>;
	using PFN_glutEstablishOverlay           = std::function<decltype(::glutEstablishOverlay)>;
	using PFN_glutRemoveOverlay              = std::function<decltype(::glutRemoveOverlay)>;
	using PFN_glutUseLayer                   = std::function<decltype(::glutUseLayer)>;
	using PFN_glutPostOverlayRedisplay       = std::function<decltype(::glutPostOverlayRedisplay)>;
	using PFN_glutPostWindowOverlayRedisplay = std::function<decltype(::glutPostWindowOverlayRedisplay)>;
	using PFN_glutShowOverlay                = std::function<decltype(::glutShowOverlay)>;
	using PFN_glutHideOverlay                = std::function<decltype(::glutHideOverlay)>;
	using PFN_glutCreateMenu                 = std::function<decltype(::glutCreateMenu)>;
	using PFN_glutDestroyMenu                = std::function<decltype(::glutDestroyMenu)>;
	using PFN_glutGetMenu                    = std::function<decltype(::glutGetMenu)>;
	using PFN_glutSetMenu                    = std::function<decltype(::glutSetMenu)>;
	using PFN_glutAddMenuEntry               = std::function<decltype(::glutAddMenuEntry)>;
	using PFN_glutAddSubMenu                 = std::function<decltype(::glutAddSubMenu)>;
	using PFN_glutChangeToMenuEntry          = std::function<decltype(::glutChangeToMenuEntry)>;
	using PFN_glutChangeToSubMenu            = std::function<decltype(::glutChangeToSubMenu)>;
	using PFN_glutRemoveMenuItem             = std::function<decltype(::glutRemoveMenuItem)>;
	using PFN_glutAttachMenu                 = std::function<decltype(::glutAttachMenu)>;
	using PFN_glutDetachMenu                 = std::function<decltype(::glutDetachMenu)>;
	using PFN_glutTimerFunc                  = std::function<decltype(::glutTimerFunc)>;
	using PFN_glutIdleFunc                   = std::function<decltype(::glutIdleFunc)>;
	using PFN_glutKeyboardFunc               = std::function<decltype(::glutKeyboardFunc)>;
	using PFN_glutSpecialFunc                = std::function<decltype(::glutSpecialFunc)>;
	using PFN_glutReshapeFunc                = std::function<decltype(::glutReshapeFunc)>;
	using PFN_glutVisibilityFunc             = std::function<decltype(::glutVisibilityFunc)>;
	using PFN_glutDisplayFunc                = std::function<decltype(::glutDisplayFunc)>;
	using PFN_glutMouseFunc                  = std::function<decltype(::glutMouseFunc)>;
	using PFN_glutMotionFunc                 = std::function<decltype(::glutMotionFunc)>;
	using PFN_glutPassiveMotionFunc          = std::function<decltype(::glutPassiveMotionFunc)>;
	using PFN_glutEntryFunc                  = std::function<decltype(::glutEntryFunc)>;
	using PFN_glutKeyboardUpFunc             = std::function<decltype(::glutKeyboardUpFunc)>;
	using PFN_glutSpecialUpFunc              = std::function<decltype(::glutSpecialUpFunc)>;
	using PFN_glutJoystickFunc               = std::function<decltype(::glutJoystickFunc)>;
	using PFN_glutMenuStateFunc              = std::function<decltype(::glutMenuStateFunc)>;
	using PFN_glutMenuStatusFunc             = std::function<decltype(::glutMenuStatusFunc)>;
	using PFN_glutOverlayDisplayFunc         = std::function<decltype(::glutOverlayDisplayFunc)>;
	using PFN_glutWindowStatusFunc           = std::function<decltype(::glutWindowStatusFunc)>;
	using PFN_glutSpaceballMotionFunc        = std::function<decltype(::glutSpaceballMotionFunc)>;
	using PFN_glutSpaceballRotateFunc        = std::function<decltype(::glutSpaceballRotateFunc)>;
	using PFN_glutSpaceballButtonFunc        = std::function<decltype(::glutSpaceballButtonFunc)>;
	using PFN_glutButtonBoxFunc              = std::function<decltype(::glutButtonBoxFunc)>;
	using PFN_glutDialsFunc                  = std::function<decltype(::glutDialsFunc)>;
	using PFN_glutTabletMotionFunc           = std::function<decltype(::glutTabletMotionFunc)>;
	using PFN_glutTabletButtonFunc           = std::function<decltype(::glutTabletButtonFunc)>;
	using PFN_glutGet                        = std::function<decltype(::glutGet)>;
	using PFN_glutDeviceGet                  = std::function<decltype(::glutDeviceGet)>;
	using PFN_glutGetModifiers               = std::function<decltype(::glutGetModifiers)>;
	using PFN_glutLayerGet                   = std::function<decltype(::glutLayerGet)>;
	using PFN_glutBitmapCharacter            = std::function<decltype(::glutBitmapCharacter)>;
	using PFN_glutBitmapWidth                = std::function<decltype(::glutBitmapWidth)>;
	using PFN_glutStrokeCharacter            = std::function<decltype(::glutStrokeCharacter)>;
	using PFN_glutStrokeWidth                = std::function<decltype(::glutStrokeWidth)>;
	using PFN_glutStrokeWidthf               = std::function<decltype(::glutStrokeWidthf)>;
	using PFN_glutBitmapLength               = std::function<decltype(::glutBitmapLength)>;
	using PFN_glutStrokeLength               = std::function<decltype(::glutStrokeLength)>;
	using PFN_glutStrokeLengthf              = std::function<decltype(::glutStrokeLengthf)>;
	using PFN_glutWireCube                   = std::function<decltype(::glutWireCube)>;
	using PFN_glutSolidCube                  = std::function<decltype(::glutSolidCube)>;
	using PFN_glutWireSphere                 = std::function<decltype(::glutWireSphere)>;
	using PFN_glutSolidSphere                = std::function<decltype(::glutSolidSphere)>;
	using PFN_glutWireCone                   = std::function<decltype(::glutWireCone)>;
	using PFN_glutSolidCone                  = std::function<decltype(::glutSolidCone)>;
	using PFN_glutWireTorus                  = std::function<decltype(::glutWireTorus)>;
	using PFN_glutSolidTorus                 = std::function<decltype(::glutSolidTorus)>;
	using PFN_glutWireDodecahedron           = std::function<decltype(::glutWireDodecahedron)>;
	using PFN_glutSolidDodecahedron          = std::function<decltype(::glutSolidDodecahedron)>;
	using PFN_glutWireOctahedron             = std::function<decltype(::glutWireOctahedron)>;
	using PFN_glutSolidOctahedron            = std::function<decltype(::glutSolidOctahedron)>;
	using PFN_glutWireTetrahedron            = std::function<decltype(::glutWireTetrahedron)>;
	using PFN_glutSolidTetrahedron           = std::function<decltype(::glutSolidTetrahedron)>;
	using PFN_glutWireIcosahedron            = std::function<decltype(::glutWireIcosahedron)>;
	using PFN_glutSolidIcosahedron           = std::function<decltype(::glutSolidIcosahedron)>;
	using PFN_glutWireTeapot                 = std::function<decltype(::glutWireTeapot)>;
	using PFN_glutSolidTeapot                = std::function<decltype(::glutSolidTeapot)>;
	using PFN_glutGameModeString             = std::function<decltype(::glutGameModeString)>;
	using PFN_glutEnterGameMode              = std::function<decltype(::glutEnterGameMode)>;
	using PFN_glutLeaveGameMode              = std::function<decltype(::glutLeaveGameMode)>;
	using PFN_glutGameModeGet                = std::function<decltype(::glutGameModeGet)>;
	using PFN_glutVideoResizeGet             = std::function<decltype(::glutVideoResizeGet)>;
	using PFN_glutSetupVideoResizing         = std::function<decltype(::glutSetupVideoResizing)>;
	using PFN_glutStopVideoResizing          = std::function<decltype(::glutStopVideoResizing)>;
	using PFN_glutVideoResize                = std::function<decltype(::glutVideoResize)>;
	using PFN_glutVideoPan                   = std::function<decltype(::glutVideoPan)>;
	using PFN_glutSetColor                   = std::function<decltype(::glutSetColor)>;
	using PFN_glutGetColor                   = std::function<decltype(::glutGetColor)>;
	using PFN_glutCopyColormap               = std::function<decltype(::glutCopyColormap)>;
	using PFN_glutIgnoreKeyRepeat            = std::function<decltype(::glutIgnoreKeyRepeat)>;
	using PFN_glutSetKeyRepeat               = std::function<decltype(::glutSetKeyRepeat)>;
	using PFN_glutForceJoystickFunc          = std::function<decltype(::glutForceJoystickFunc)>;
	using PFN_glutExtensionSupported         = std::function<decltype(::glutExtensionSupported)>;
	using PFN_glutReportErrors               = std::function<decltype(::glutReportErrors)>;
	using PFN_glutMainLoopEvent              = std::function<decltype(::glutMainLoopEvent)>;
	using PFN_glutLeaveMainLoop              = std::function<decltype(::glutLeaveMainLoop)>;
	using PFN_glutExit                       = std::function<decltype(::glutExit         )>;
	using PFN_glutFullScreenToggle           = std::function<decltype(::glutFullScreenToggle)>;
	using PFN_glutLeaveFullScreen            = std::function<decltype(::glutLeaveFullScreen)>;
	using PFN_glutSetMenuFont                = std::function<decltype(::glutSetMenuFont)>;
	using PFN_glutMouseWheelFunc             = std::function<decltype(::glutMouseWheelFunc)>;
	using PFN_glutPositionFunc               = std::function<decltype(::glutPositionFunc)>;
	using PFN_glutCloseFunc                  = std::function<decltype(::glutCloseFunc)>;
	using PFN_glutWMCloseFunc                = std::function<decltype(::glutWMCloseFunc)>;
	using PFN_glutMenuDestroyFunc            = std::function<decltype(::glutMenuDestroyFunc)>;
	using PFN_glutSetOption                  = std::function<decltype(::glutSetOption )>;
	using PFN_glutGetModeValues              = std::function<decltype(::glutGetModeValues)>;
	using PFN_glutGetWindowData              = std::function<decltype(::glutGetWindowData)>;
	using PFN_glutSetWindowData              = std::function<decltype(::glutSetWindowData)>;
	using PFN_glutGetMenuData                = std::function<decltype(::glutGetMenuData)>;
	using PFN_glutSetMenuData                = std::function<decltype(::glutSetMenuData)>;
	using PFN_glutBitmapHeight               = std::function<decltype(::glutBitmapHeight)>;
	using PFN_glutStrokeHeight               = std::function<decltype(::glutStrokeHeight)>;
	using PFN_glutBitmapString               = std::function<decltype(::glutBitmapString)>;
	using PFN_glutStrokeString               = std::function<decltype(::glutStrokeString)>;
	using PFN_glutWireRhombicDodecahedron    = std::function<decltype(::glutWireRhombicDodecahedron)>;
	using PFN_glutSolidRhombicDodecahedron   = std::function<decltype(::glutSolidRhombicDodecahedron)>;
	using PFN_glutWireSierpinskiSponge       = std::function<decltype(::glutWireSierpinskiSponge )>;
	using PFN_glutSolidSierpinskiSponge      = std::function<decltype(::glutSolidSierpinskiSponge )>;
	using PFN_glutWireCylinder               = std::function<decltype(::glutWireCylinder)>;
	using PFN_glutSolidCylinder              = std::function<decltype(::glutSolidCylinder)>;
	using PFN_glutWireTeacup                 = std::function<decltype(::glutWireTeacup)>;
	using PFN_glutSolidTeacup                = std::function<decltype(::glutSolidTeacup)>;
	using PFN_glutWireTeaspoon               = std::function<decltype(::glutWireTeaspoon)>;
	using PFN_glutSolidTeaspoon              = std::function<decltype(::glutSolidTeaspoon)>;
	using PFN_glutGetProcAddress             = std::function<decltype(::glutGetProcAddress)>;
	using PFN_glutMultiEntryFunc             = std::function<decltype(::glutMultiEntryFunc)>;
	using PFN_glutMultiButtonFunc            = std::function<decltype(::glutMultiButtonFunc)>;
	using PFN_glutMultiMotionFunc            = std::function<decltype(::glutMultiMotionFunc)>;
	using PFN_glutMultiPassiveFunc           = std::function<decltype(::glutMultiPassiveFunc)>;
	using PFN_glutInitContextVersion         = std::function<decltype(::glutInitContextVersion)>;
	using PFN_glutInitContextFlags           = std::function<decltype(::glutInitContextFlags)>;
	using PFN_glutInitContextProfile         = std::function<decltype(::glutInitContextProfile)>;
	using PFN_glutInitErrorFunc              = std::function<decltype(::glutInitErrorFunc)>;
	using PFN_glutInitWarningFunc            = std::function<decltype(::glutInitWarningFunc)>;
	using PFN_glutSetVertexAttribCoord3      = std::function<decltype(::glutSetVertexAttribCoord3)>;
	using PFN_glutSetVertexAttribNormal      = std::function<decltype(::glutSetVertexAttribNormal)>;
	using PFN_glutSetVertexAttribTexCoord2   = std::function<decltype(::glutSetVertexAttribTexCoord2)>;
	using PFN_glutInitContextFunc            = std::function<decltype(::glutInitContextFunc)>;
	using PFN_glutAppStatusFunc              = std::function<decltype(::glutAppStatusFunc)>;
	extern PFN_glutInit                       fn_glutInit;
	extern PFN_glutInitWindowPosition         fn_glutInitWindowPosition;
	extern PFN_glutInitWindowSize             fn_glutInitWindowSize;
	extern PFN_glutInitDisplayMode            fn_glutInitDisplayMode;
	extern PFN_glutInitDisplayString          fn_glutInitDisplayString;
	extern PFN_glutMainLoop                   fn_glutMainLoop;
	extern PFN_glutCreateWindow               fn_glutCreateWindow;
	extern PFN_glutCreateSubWindow            fn_glutCreateSubWindow;
	extern PFN_glutDestroyWindow              fn_glutDestroyWindow;
	extern PFN_glutSetWindow                  fn_glutSetWindow;
	extern PFN_glutGetWindow                  fn_glutGetWindow;
	extern PFN_glutSetWindowTitle             fn_glutSetWindowTitle;
	extern PFN_glutSetIconTitle               fn_glutSetIconTitle;
	extern PFN_glutReshapeWindow              fn_glutReshapeWindow;
	extern PFN_glutPositionWindow             fn_glutPositionWindow;
	extern PFN_glutShowWindow                 fn_glutShowWindow;
	extern PFN_glutHideWindow                 fn_glutHideWindow;
	extern PFN_glutIconifyWindow              fn_glutIconifyWindow;
	extern PFN_glutPushWindow                 fn_glutPushWindow;
	extern PFN_glutPopWindow                  fn_glutPopWindow;
	extern PFN_glutFullScreen                 fn_glutFullScreen;
	extern PFN_glutPostWindowRedisplay        fn_glutPostWindowRedisplay;
	extern PFN_glutPostRedisplay              fn_glutPostRedisplay;
	extern PFN_glutSwapBuffers                fn_glutSwapBuffers;
	extern PFN_glutWarpPointer                fn_glutWarpPointer;
	extern PFN_glutSetCursor                  fn_glutSetCursor;
	extern PFN_glutEstablishOverlay           fn_glutEstablishOverlay;
	extern PFN_glutRemoveOverlay              fn_glutRemoveOverlay;
	extern PFN_glutUseLayer                   fn_glutUseLayer;
	extern PFN_glutPostOverlayRedisplay       fn_glutPostOverlayRedisplay;
	extern PFN_glutPostWindowOverlayRedisplay fn_glutPostWindowOverlayRedisplay;
	extern PFN_glutShowOverlay                fn_glutShowOverlay;
	extern PFN_glutHideOverlay                fn_glutHideOverlay;
	extern PFN_glutCreateMenu                 fn_glutCreateMenu;
	extern PFN_glutDestroyMenu                fn_glutDestroyMenu;
	extern PFN_glutGetMenu                    fn_glutGetMenu;
	extern PFN_glutSetMenu                    fn_glutSetMenu;
	extern PFN_glutAddMenuEntry               fn_glutAddMenuEntry;
	extern PFN_glutAddSubMenu                 fn_glutAddSubMenu;
	extern PFN_glutChangeToMenuEntry          fn_glutChangeToMenuEntry;
	extern PFN_glutChangeToSubMenu            fn_glutChangeToSubMenu;
	extern PFN_glutRemoveMenuItem             fn_glutRemoveMenuItem;
	extern PFN_glutAttachMenu                 fn_glutAttachMenu;
	extern PFN_glutDetachMenu                 fn_glutDetachMenu;
	extern PFN_glutTimerFunc                  fn_glutTimerFunc;
	extern PFN_glutIdleFunc                   fn_glutIdleFunc;
	extern PFN_glutKeyboardFunc               fn_glutKeyboardFunc;
	extern PFN_glutSpecialFunc                fn_glutSpecialFunc;
	extern PFN_glutReshapeFunc                fn_glutReshapeFunc;
	extern PFN_glutVisibilityFunc             fn_glutVisibilityFunc;
	extern PFN_glutDisplayFunc                fn_glutDisplayFunc;
	extern PFN_glutMouseFunc                  fn_glutMouseFunc;
	extern PFN_glutMotionFunc                 fn_glutMotionFunc;
	extern PFN_glutPassiveMotionFunc          fn_glutPassiveMotionFunc;
	extern PFN_glutEntryFunc                  fn_glutEntryFunc;
	extern PFN_glutKeyboardUpFunc             fn_glutKeyboardUpFunc;
	extern PFN_glutSpecialUpFunc              fn_glutSpecialUpFunc;
	extern PFN_glutJoystickFunc               fn_glutJoystickFunc;
	extern PFN_glutMenuStateFunc              fn_glutMenuStateFunc;
	extern PFN_glutMenuStatusFunc             fn_glutMenuStatusFunc;
	extern PFN_glutOverlayDisplayFunc         fn_glutOverlayDisplayFunc;
	extern PFN_glutWindowStatusFunc           fn_glutWindowStatusFunc;
	extern PFN_glutSpaceballMotionFunc        fn_glutSpaceballMotionFunc;
	extern PFN_glutSpaceballRotateFunc        fn_glutSpaceballRotateFunc;
	extern PFN_glutSpaceballButtonFunc        fn_glutSpaceballButtonFunc;
	extern PFN_glutButtonBoxFunc              fn_glutButtonBoxFunc;
	extern PFN_glutDialsFunc                  fn_glutDialsFunc;
	extern PFN_glutTabletMotionFunc           fn_glutTabletMotionFunc;
	extern PFN_glutTabletButtonFunc           fn_glutTabletButtonFunc;
	extern PFN_glutGet                        fn_glutGet;
	extern PFN_glutDeviceGet                  fn_glutDeviceGet;
	extern PFN_glutGetModifiers               fn_glutGetModifiers;
	extern PFN_glutLayerGet                   fn_glutLayerGet;
	extern PFN_glutBitmapCharacter            fn_glutBitmapCharacter;
	extern PFN_glutBitmapWidth                fn_glutBitmapWidth;
	extern PFN_glutStrokeCharacter            fn_glutStrokeCharacter;
	extern PFN_glutStrokeWidth                fn_glutStrokeWidth;
	extern PFN_glutStrokeWidthf               fn_glutStrokeWidthf;
	extern PFN_glutBitmapLength               fn_glutBitmapLength;
	extern PFN_glutStrokeLength               fn_glutStrokeLength;
	extern PFN_glutStrokeLengthf              fn_glutStrokeLengthf;
	extern PFN_glutWireCube                   fn_glutWireCube;
	extern PFN_glutSolidCube                  fn_glutSolidCube;
	extern PFN_glutWireSphere                 fn_glutWireSphere;
	extern PFN_glutSolidSphere                fn_glutSolidSphere;
	extern PFN_glutWireCone                   fn_glutWireCone;
	extern PFN_glutSolidCone                  fn_glutSolidCone;
	extern PFN_glutWireTorus                  fn_glutWireTorus;
	extern PFN_glutSolidTorus                 fn_glutSolidTorus;
	extern PFN_glutWireDodecahedron           fn_glutWireDodecahedron;
	extern PFN_glutSolidDodecahedron          fn_glutSolidDodecahedron;
	extern PFN_glutWireOctahedron             fn_glutWireOctahedron;
	extern PFN_glutSolidOctahedron            fn_glutSolidOctahedron;
	extern PFN_glutWireTetrahedron            fn_glutWireTetrahedron;
	extern PFN_glutSolidTetrahedron           fn_glutSolidTetrahedron;
	extern PFN_glutWireIcosahedron            fn_glutWireIcosahedron;
	extern PFN_glutSolidIcosahedron           fn_glutSolidIcosahedron;
	extern PFN_glutWireTeapot                 fn_glutWireTeapot;
	extern PFN_glutSolidTeapot                fn_glutSolidTeapot;
	extern PFN_glutGameModeString             fn_glutGameModeString;
	extern PFN_glutEnterGameMode              fn_glutEnterGameMode;
	extern PFN_glutLeaveGameMode              fn_glutLeaveGameMode;
	extern PFN_glutGameModeGet                fn_glutGameModeGet;
	extern PFN_glutVideoResizeGet             fn_glutVideoResizeGet;
	extern PFN_glutSetupVideoResizing         fn_glutSetupVideoResizing;
	extern PFN_glutStopVideoResizing          fn_glutStopVideoResizing;
	extern PFN_glutVideoResize                fn_glutVideoResize;
	extern PFN_glutVideoPan                   fn_glutVideoPan;
	extern PFN_glutSetColor                   fn_glutSetColor;
	extern PFN_glutGetColor                   fn_glutGetColor;
	extern PFN_glutCopyColormap               fn_glutCopyColormap;
	extern PFN_glutIgnoreKeyRepeat            fn_glutIgnoreKeyRepeat;
	extern PFN_glutSetKeyRepeat               fn_glutSetKeyRepeat;
	extern PFN_glutForceJoystickFunc          fn_glutForceJoystickFunc;
	extern PFN_glutExtensionSupported         fn_glutExtensionSupported;
	extern PFN_glutReportErrors               fn_glutReportErrors;
	extern PFN_glutMainLoopEvent              fn_glutMainLoopEvent;
	extern PFN_glutLeaveMainLoop              fn_glutLeaveMainLoop;
	extern PFN_glutExit                       fn_glutExit         ;
	extern PFN_glutFullScreenToggle           fn_glutFullScreenToggle;
	extern PFN_glutLeaveFullScreen            fn_glutLeaveFullScreen;
	extern PFN_glutSetMenuFont                fn_glutSetMenuFont;
	extern PFN_glutMouseWheelFunc             fn_glutMouseWheelFunc;
	extern PFN_glutPositionFunc               fn_glutPositionFunc;
	extern PFN_glutCloseFunc                  fn_glutCloseFunc;
	extern PFN_glutWMCloseFunc                fn_glutWMCloseFunc;
	extern PFN_glutMenuDestroyFunc            fn_glutMenuDestroyFunc;
	extern PFN_glutSetOption                  fn_glutSetOption ;
	extern PFN_glutGetModeValues              fn_glutGetModeValues;
	extern PFN_glutGetWindowData              fn_glutGetWindowData;
	extern PFN_glutSetWindowData              fn_glutSetWindowData;
	extern PFN_glutGetMenuData                fn_glutGetMenuData;
	extern PFN_glutSetMenuData                fn_glutSetMenuData;
	extern PFN_glutBitmapHeight               fn_glutBitmapHeight;
	extern PFN_glutStrokeHeight               fn_glutStrokeHeight;
	extern PFN_glutBitmapString               fn_glutBitmapString;
	extern PFN_glutStrokeString               fn_glutStrokeString;
	extern PFN_glutWireRhombicDodecahedron    fn_glutWireRhombicDodecahedron;
	extern PFN_glutSolidRhombicDodecahedron   fn_glutSolidRhombicDodecahedron;
	extern PFN_glutWireSierpinskiSponge       fn_glutWireSierpinskiSponge ;
	extern PFN_glutSolidSierpinskiSponge      fn_glutSolidSierpinskiSponge ;
	extern PFN_glutWireCylinder               fn_glutWireCylinder;
	extern PFN_glutSolidCylinder              fn_glutSolidCylinder;
	extern PFN_glutWireTeacup                 fn_glutWireTeacup;
	extern PFN_glutSolidTeacup                fn_glutSolidTeacup;
	extern PFN_glutWireTeaspoon               fn_glutWireTeaspoon;
	extern PFN_glutSolidTeaspoon              fn_glutSolidTeaspoon;
	extern PFN_glutGetProcAddress             fn_glutGetProcAddress;
	extern PFN_glutMultiEntryFunc             fn_glutMultiEntryFunc;
	extern PFN_glutMultiButtonFunc            fn_glutMultiButtonFunc;
	extern PFN_glutMultiMotionFunc            fn_glutMultiMotionFunc;
	extern PFN_glutMultiPassiveFunc           fn_glutMultiPassiveFunc;
	extern PFN_glutInitContextVersion         fn_glutInitContextVersion;
	extern PFN_glutInitContextFlags           fn_glutInitContextFlags;
	extern PFN_glutInitContextProfile         fn_glutInitContextProfile;
	extern PFN_glutInitErrorFunc              fn_glutInitErrorFunc;
	extern PFN_glutInitWarningFunc            fn_glutInitWarningFunc;
	extern PFN_glutSetVertexAttribCoord3      fn_glutSetVertexAttribCoord3;
	extern PFN_glutSetVertexAttribNormal      fn_glutSetVertexAttribNormal;
	extern PFN_glutSetVertexAttribTexCoord2   fn_glutSetVertexAttribTexCoord2;
	extern PFN_glutInitContextFunc            fn_glutInitContextFunc;
	extern PFN_glutAppStatusFunc              fn_glutAppStatusFunc;

}
