#include "freeglut_wrapper.h"
#include "badger/assertion/assertion.h"

#include <Windows.h>
#include "GL/freeglut.h"

static HMODULE dll = NULL;

namespace FreeGLUT {

	void unloadDLL() {
		CHECK(dll != NULL);
		::FreeLibrary(dll);
		dll = NULL;
	}

	void loadDLL() {
		CHECK(dll == NULL);
		dll = ::LoadLibraryA("freeglut.dll");
		CHECKF(dll != NULL, "Failed to load freeglut.dll");

		// Auto-generated
		FreeGLUT::fn_glutInit                       = (decltype(&glutInit))::GetProcAddress(dll, "glutInit");
		FreeGLUT::fn_glutInitWindowPosition         = (decltype(&glutInitWindowPosition))::GetProcAddress(dll, "glutInitWindowPosition");
		FreeGLUT::fn_glutInitWindowSize             = (decltype(&glutInitWindowSize))::GetProcAddress(dll, "glutInitWindowSize");
		FreeGLUT::fn_glutInitDisplayMode            = (decltype(&glutInitDisplayMode))::GetProcAddress(dll, "glutInitDisplayMode");
		FreeGLUT::fn_glutInitDisplayString          = (decltype(&glutInitDisplayString))::GetProcAddress(dll, "glutInitDisplayString");
		FreeGLUT::fn_glutMainLoop                   = (decltype(&glutMainLoop))::GetProcAddress(dll, "glutMainLoop");
		FreeGLUT::fn_glutCreateWindow               = (decltype(&glutCreateWindow))::GetProcAddress(dll, "glutCreateWindow");
		FreeGLUT::fn_glutCreateSubWindow            = (decltype(&glutCreateSubWindow))::GetProcAddress(dll, "glutCreateSubWindow");
		FreeGLUT::fn_glutDestroyWindow              = (decltype(&glutDestroyWindow))::GetProcAddress(dll, "glutDestroyWindow");
		FreeGLUT::fn_glutSetWindow                  = (decltype(&glutSetWindow))::GetProcAddress(dll, "glutSetWindow");
		FreeGLUT::fn_glutGetWindow                  = (decltype(&glutGetWindow))::GetProcAddress(dll, "glutGetWindow");
		FreeGLUT::fn_glutSetWindowTitle             = (decltype(&glutSetWindowTitle))::GetProcAddress(dll, "glutSetWindowTitle");
		FreeGLUT::fn_glutSetIconTitle               = (decltype(&glutSetIconTitle))::GetProcAddress(dll, "glutSetIconTitle");
		FreeGLUT::fn_glutReshapeWindow              = (decltype(&glutReshapeWindow))::GetProcAddress(dll, "glutReshapeWindow");
		FreeGLUT::fn_glutPositionWindow             = (decltype(&glutPositionWindow))::GetProcAddress(dll, "glutPositionWindow");
		FreeGLUT::fn_glutShowWindow                 = (decltype(&glutShowWindow))::GetProcAddress(dll, "glutShowWindow");
		FreeGLUT::fn_glutHideWindow                 = (decltype(&glutHideWindow))::GetProcAddress(dll, "glutHideWindow");
		FreeGLUT::fn_glutIconifyWindow              = (decltype(&glutIconifyWindow))::GetProcAddress(dll, "glutIconifyWindow");
		FreeGLUT::fn_glutPushWindow                 = (decltype(&glutPushWindow))::GetProcAddress(dll, "glutPushWindow");
		FreeGLUT::fn_glutPopWindow                  = (decltype(&glutPopWindow))::GetProcAddress(dll, "glutPopWindow");
		FreeGLUT::fn_glutFullScreen                 = (decltype(&glutFullScreen))::GetProcAddress(dll, "glutFullScreen");
		FreeGLUT::fn_glutPostWindowRedisplay        = (decltype(&glutPostWindowRedisplay))::GetProcAddress(dll, "glutPostWindowRedisplay");
		FreeGLUT::fn_glutPostRedisplay              = (decltype(&glutPostRedisplay))::GetProcAddress(dll, "glutPostRedisplay");
		FreeGLUT::fn_glutSwapBuffers                = (decltype(&glutSwapBuffers))::GetProcAddress(dll, "glutSwapBuffers");
		FreeGLUT::fn_glutWarpPointer                = (decltype(&glutWarpPointer))::GetProcAddress(dll, "glutWarpPointer");
		FreeGLUT::fn_glutSetCursor                  = (decltype(&glutSetCursor))::GetProcAddress(dll, "glutSetCursor");
		FreeGLUT::fn_glutEstablishOverlay           = (decltype(&glutEstablishOverlay))::GetProcAddress(dll, "glutEstablishOverlay");
		FreeGLUT::fn_glutRemoveOverlay              = (decltype(&glutRemoveOverlay))::GetProcAddress(dll, "glutRemoveOverlay");
		FreeGLUT::fn_glutUseLayer                   = (decltype(&glutUseLayer))::GetProcAddress(dll, "glutUseLayer");
		FreeGLUT::fn_glutPostOverlayRedisplay       = (decltype(&glutPostOverlayRedisplay))::GetProcAddress(dll, "glutPostOverlayRedisplay");
		FreeGLUT::fn_glutPostWindowOverlayRedisplay = (decltype(&glutPostWindowOverlayRedisplay))::GetProcAddress(dll, "glutPostWindowOverlayRedisplay");
		FreeGLUT::fn_glutShowOverlay                = (decltype(&glutShowOverlay))::GetProcAddress(dll, "glutShowOverlay");
		FreeGLUT::fn_glutHideOverlay                = (decltype(&glutHideOverlay))::GetProcAddress(dll, "glutHideOverlay");
		FreeGLUT::fn_glutCreateMenu                 = (decltype(&glutCreateMenu))::GetProcAddress(dll, "glutCreateMenu");
		FreeGLUT::fn_glutDestroyMenu                = (decltype(&glutDestroyMenu))::GetProcAddress(dll, "glutDestroyMenu");
		FreeGLUT::fn_glutGetMenu                    = (decltype(&glutGetMenu))::GetProcAddress(dll, "glutGetMenu");
		FreeGLUT::fn_glutSetMenu                    = (decltype(&glutSetMenu))::GetProcAddress(dll, "glutSetMenu");
		FreeGLUT::fn_glutAddMenuEntry               = (decltype(&glutAddMenuEntry))::GetProcAddress(dll, "glutAddMenuEntry");
		FreeGLUT::fn_glutAddSubMenu                 = (decltype(&glutAddSubMenu))::GetProcAddress(dll, "glutAddSubMenu");
		FreeGLUT::fn_glutChangeToMenuEntry          = (decltype(&glutChangeToMenuEntry))::GetProcAddress(dll, "glutChangeToMenuEntry");
		FreeGLUT::fn_glutChangeToSubMenu            = (decltype(&glutChangeToSubMenu))::GetProcAddress(dll, "glutChangeToSubMenu");
		FreeGLUT::fn_glutRemoveMenuItem             = (decltype(&glutRemoveMenuItem))::GetProcAddress(dll, "glutRemoveMenuItem");
		FreeGLUT::fn_glutAttachMenu                 = (decltype(&glutAttachMenu))::GetProcAddress(dll, "glutAttachMenu");
		FreeGLUT::fn_glutDetachMenu                 = (decltype(&glutDetachMenu))::GetProcAddress(dll, "glutDetachMenu");
		FreeGLUT::fn_glutTimerFunc                  = (decltype(&glutTimerFunc))::GetProcAddress(dll, "glutTimerFunc");
		FreeGLUT::fn_glutIdleFunc                   = (decltype(&glutIdleFunc))::GetProcAddress(dll, "glutIdleFunc");
		FreeGLUT::fn_glutKeyboardFunc               = (decltype(&glutKeyboardFunc))::GetProcAddress(dll, "glutKeyboardFunc");
		FreeGLUT::fn_glutSpecialFunc                = (decltype(&glutSpecialFunc))::GetProcAddress(dll, "glutSpecialFunc");
		FreeGLUT::fn_glutReshapeFunc                = (decltype(&glutReshapeFunc))::GetProcAddress(dll, "glutReshapeFunc");
		FreeGLUT::fn_glutVisibilityFunc             = (decltype(&glutVisibilityFunc))::GetProcAddress(dll, "glutVisibilityFunc");
		FreeGLUT::fn_glutDisplayFunc                = (decltype(&glutDisplayFunc))::GetProcAddress(dll, "glutDisplayFunc");
		FreeGLUT::fn_glutMouseFunc                  = (decltype(&glutMouseFunc))::GetProcAddress(dll, "glutMouseFunc");
		FreeGLUT::fn_glutMotionFunc                 = (decltype(&glutMotionFunc))::GetProcAddress(dll, "glutMotionFunc");
		FreeGLUT::fn_glutPassiveMotionFunc          = (decltype(&glutPassiveMotionFunc))::GetProcAddress(dll, "glutPassiveMotionFunc");
		FreeGLUT::fn_glutEntryFunc                  = (decltype(&glutEntryFunc))::GetProcAddress(dll, "glutEntryFunc");
		FreeGLUT::fn_glutKeyboardUpFunc             = (decltype(&glutKeyboardUpFunc))::GetProcAddress(dll, "glutKeyboardUpFunc");
		FreeGLUT::fn_glutSpecialUpFunc              = (decltype(&glutSpecialUpFunc))::GetProcAddress(dll, "glutSpecialUpFunc");
		FreeGLUT::fn_glutJoystickFunc               = (decltype(&glutJoystickFunc))::GetProcAddress(dll, "glutJoystickFunc");
		FreeGLUT::fn_glutMenuStateFunc              = (decltype(&glutMenuStateFunc))::GetProcAddress(dll, "glutMenuStateFunc");
		FreeGLUT::fn_glutMenuStatusFunc             = (decltype(&glutMenuStatusFunc))::GetProcAddress(dll, "glutMenuStatusFunc");
		FreeGLUT::fn_glutOverlayDisplayFunc         = (decltype(&glutOverlayDisplayFunc))::GetProcAddress(dll, "glutOverlayDisplayFunc");
		FreeGLUT::fn_glutWindowStatusFunc           = (decltype(&glutWindowStatusFunc))::GetProcAddress(dll, "glutWindowStatusFunc");
		FreeGLUT::fn_glutSpaceballMotionFunc        = (decltype(&glutSpaceballMotionFunc))::GetProcAddress(dll, "glutSpaceballMotionFunc");
		FreeGLUT::fn_glutSpaceballRotateFunc        = (decltype(&glutSpaceballRotateFunc))::GetProcAddress(dll, "glutSpaceballRotateFunc");
		FreeGLUT::fn_glutSpaceballButtonFunc        = (decltype(&glutSpaceballButtonFunc))::GetProcAddress(dll, "glutSpaceballButtonFunc");
		FreeGLUT::fn_glutButtonBoxFunc              = (decltype(&glutButtonBoxFunc))::GetProcAddress(dll, "glutButtonBoxFunc");
		FreeGLUT::fn_glutDialsFunc                  = (decltype(&glutDialsFunc))::GetProcAddress(dll, "glutDialsFunc");
		FreeGLUT::fn_glutTabletMotionFunc           = (decltype(&glutTabletMotionFunc))::GetProcAddress(dll, "glutTabletMotionFunc");
		FreeGLUT::fn_glutTabletButtonFunc           = (decltype(&glutTabletButtonFunc))::GetProcAddress(dll, "glutTabletButtonFunc");
		FreeGLUT::fn_glutGet                        = (decltype(&glutGet))::GetProcAddress(dll, "glutGet");
		FreeGLUT::fn_glutDeviceGet                  = (decltype(&glutDeviceGet))::GetProcAddress(dll, "glutDeviceGet");
		FreeGLUT::fn_glutGetModifiers               = (decltype(&glutGetModifiers))::GetProcAddress(dll, "glutGetModifiers");
		FreeGLUT::fn_glutLayerGet                   = (decltype(&glutLayerGet))::GetProcAddress(dll, "glutLayerGet");
		FreeGLUT::fn_glutBitmapCharacter            = (decltype(&glutBitmapCharacter))::GetProcAddress(dll, "glutBitmapCharacter");
		FreeGLUT::fn_glutBitmapWidth                = (decltype(&glutBitmapWidth))::GetProcAddress(dll, "glutBitmapWidth");
		FreeGLUT::fn_glutStrokeCharacter            = (decltype(&glutStrokeCharacter))::GetProcAddress(dll, "glutStrokeCharacter");
		FreeGLUT::fn_glutStrokeWidth                = (decltype(&glutStrokeWidth))::GetProcAddress(dll, "glutStrokeWidth");
		FreeGLUT::fn_glutStrokeWidthf               = (decltype(&glutStrokeWidthf))::GetProcAddress(dll, "glutStrokeWidthf");
		FreeGLUT::fn_glutBitmapLength               = (decltype(&glutBitmapLength))::GetProcAddress(dll, "glutBitmapLength");
		FreeGLUT::fn_glutStrokeLength               = (decltype(&glutStrokeLength))::GetProcAddress(dll, "glutStrokeLength");
		FreeGLUT::fn_glutStrokeLengthf              = (decltype(&glutStrokeLengthf))::GetProcAddress(dll, "glutStrokeLengthf");
		FreeGLUT::fn_glutWireCube                   = (decltype(&glutWireCube))::GetProcAddress(dll, "glutWireCube");
		FreeGLUT::fn_glutSolidCube                  = (decltype(&glutSolidCube))::GetProcAddress(dll, "glutSolidCube");
		FreeGLUT::fn_glutWireSphere                 = (decltype(&glutWireSphere))::GetProcAddress(dll, "glutWireSphere");
		FreeGLUT::fn_glutSolidSphere                = (decltype(&glutSolidSphere))::GetProcAddress(dll, "glutSolidSphere");
		FreeGLUT::fn_glutWireCone                   = (decltype(&glutWireCone))::GetProcAddress(dll, "glutWireCone");
		FreeGLUT::fn_glutSolidCone                  = (decltype(&glutSolidCone))::GetProcAddress(dll, "glutSolidCone");
		FreeGLUT::fn_glutWireTorus                  = (decltype(&glutWireTorus))::GetProcAddress(dll, "glutWireTorus");
		FreeGLUT::fn_glutSolidTorus                 = (decltype(&glutSolidTorus))::GetProcAddress(dll, "glutSolidTorus");
		FreeGLUT::fn_glutWireDodecahedron           = (decltype(&glutWireDodecahedron))::GetProcAddress(dll, "glutWireDodecahedron");
		FreeGLUT::fn_glutSolidDodecahedron          = (decltype(&glutSolidDodecahedron))::GetProcAddress(dll, "glutSolidDodecahedron");
		FreeGLUT::fn_glutWireOctahedron             = (decltype(&glutWireOctahedron))::GetProcAddress(dll, "glutWireOctahedron");
		FreeGLUT::fn_glutSolidOctahedron            = (decltype(&glutSolidOctahedron))::GetProcAddress(dll, "glutSolidOctahedron");
		FreeGLUT::fn_glutWireTetrahedron            = (decltype(&glutWireTetrahedron))::GetProcAddress(dll, "glutWireTetrahedron");
		FreeGLUT::fn_glutSolidTetrahedron           = (decltype(&glutSolidTetrahedron))::GetProcAddress(dll, "glutSolidTetrahedron");
		FreeGLUT::fn_glutWireIcosahedron            = (decltype(&glutWireIcosahedron))::GetProcAddress(dll, "glutWireIcosahedron");
		FreeGLUT::fn_glutSolidIcosahedron           = (decltype(&glutSolidIcosahedron))::GetProcAddress(dll, "glutSolidIcosahedron");
		FreeGLUT::fn_glutWireTeapot                 = (decltype(&glutWireTeapot))::GetProcAddress(dll, "glutWireTeapot");
		FreeGLUT::fn_glutSolidTeapot                = (decltype(&glutSolidTeapot))::GetProcAddress(dll, "glutSolidTeapot");
		FreeGLUT::fn_glutGameModeString             = (decltype(&glutGameModeString))::GetProcAddress(dll, "glutGameModeString");
		FreeGLUT::fn_glutEnterGameMode              = (decltype(&glutEnterGameMode))::GetProcAddress(dll, "glutEnterGameMode");
		FreeGLUT::fn_glutLeaveGameMode              = (decltype(&glutLeaveGameMode))::GetProcAddress(dll, "glutLeaveGameMode");
		FreeGLUT::fn_glutGameModeGet                = (decltype(&glutGameModeGet))::GetProcAddress(dll, "glutGameModeGet");
		FreeGLUT::fn_glutVideoResizeGet             = (decltype(&glutVideoResizeGet))::GetProcAddress(dll, "glutVideoResizeGet");
		FreeGLUT::fn_glutSetupVideoResizing         = (decltype(&glutSetupVideoResizing))::GetProcAddress(dll, "glutSetupVideoResizing");
		FreeGLUT::fn_glutStopVideoResizing          = (decltype(&glutStopVideoResizing))::GetProcAddress(dll, "glutStopVideoResizing");
		FreeGLUT::fn_glutVideoResize                = (decltype(&glutVideoResize))::GetProcAddress(dll, "glutVideoResize");
		FreeGLUT::fn_glutVideoPan                   = (decltype(&glutVideoPan))::GetProcAddress(dll, "glutVideoPan");
		FreeGLUT::fn_glutSetColor                   = (decltype(&glutSetColor))::GetProcAddress(dll, "glutSetColor");
		FreeGLUT::fn_glutGetColor                   = (decltype(&glutGetColor))::GetProcAddress(dll, "glutGetColor");
		FreeGLUT::fn_glutCopyColormap               = (decltype(&glutCopyColormap))::GetProcAddress(dll, "glutCopyColormap");
		FreeGLUT::fn_glutIgnoreKeyRepeat            = (decltype(&glutIgnoreKeyRepeat))::GetProcAddress(dll, "glutIgnoreKeyRepeat");
		FreeGLUT::fn_glutSetKeyRepeat               = (decltype(&glutSetKeyRepeat))::GetProcAddress(dll, "glutSetKeyRepeat");
		FreeGLUT::fn_glutForceJoystickFunc          = (decltype(&glutForceJoystickFunc))::GetProcAddress(dll, "glutForceJoystickFunc");
		FreeGLUT::fn_glutExtensionSupported         = (decltype(&glutExtensionSupported))::GetProcAddress(dll, "glutExtensionSupported");
		FreeGLUT::fn_glutReportErrors               = (decltype(&glutReportErrors))::GetProcAddress(dll, "glutReportErrors");
		FreeGLUT::fn_glutMainLoopEvent              = (decltype(&glutMainLoopEvent))::GetProcAddress(dll, "glutMainLoopEvent");
		FreeGLUT::fn_glutLeaveMainLoop              = (decltype(&glutLeaveMainLoop))::GetProcAddress(dll, "glutLeaveMainLoop");
		FreeGLUT::fn_glutExit                       = (decltype(&glutExit))::GetProcAddress(dll, "glutExit");
		FreeGLUT::fn_glutFullScreenToggle           = (decltype(&glutFullScreenToggle))::GetProcAddress(dll, "glutFullScreenToggle");
		FreeGLUT::fn_glutLeaveFullScreen            = (decltype(&glutLeaveFullScreen))::GetProcAddress(dll, "glutLeaveFullScreen");
		FreeGLUT::fn_glutSetMenuFont                = (decltype(&glutSetMenuFont))::GetProcAddress(dll, "glutSetMenuFont");
		FreeGLUT::fn_glutMouseWheelFunc             = (decltype(&glutMouseWheelFunc))::GetProcAddress(dll, "glutMouseWheelFunc");
		FreeGLUT::fn_glutPositionFunc               = (decltype(&glutPositionFunc))::GetProcAddress(dll, "glutPositionFunc");
		FreeGLUT::fn_glutCloseFunc                  = (decltype(&glutCloseFunc))::GetProcAddress(dll, "glutCloseFunc");
		FreeGLUT::fn_glutWMCloseFunc                = (decltype(&glutWMCloseFunc))::GetProcAddress(dll, "glutWMCloseFunc");
		FreeGLUT::fn_glutMenuDestroyFunc            = (decltype(&glutMenuDestroyFunc))::GetProcAddress(dll, "glutMenuDestroyFunc");
		FreeGLUT::fn_glutSetOption                  = (decltype(&glutSetOption ))::GetProcAddress(dll, "glutSetOption ");
		FreeGLUT::fn_glutGetModeValues              = (decltype(&glutGetModeValues))::GetProcAddress(dll, "glutGetModeValues");
		FreeGLUT::fn_glutGetWindowData              = (decltype(&glutGetWindowData))::GetProcAddress(dll, "glutGetWindowData");
		FreeGLUT::fn_glutSetWindowData              = (decltype(&glutSetWindowData))::GetProcAddress(dll, "glutSetWindowData");
		FreeGLUT::fn_glutGetMenuData                = (decltype(&glutGetMenuData))::GetProcAddress(dll, "glutGetMenuData");
		FreeGLUT::fn_glutSetMenuData                = (decltype(&glutSetMenuData))::GetProcAddress(dll, "glutSetMenuData");
		FreeGLUT::fn_glutBitmapHeight               = (decltype(&glutBitmapHeight))::GetProcAddress(dll, "glutBitmapHeight");
		FreeGLUT::fn_glutStrokeHeight               = (decltype(&glutStrokeHeight))::GetProcAddress(dll, "glutStrokeHeight");
		FreeGLUT::fn_glutBitmapString               = (decltype(&glutBitmapString))::GetProcAddress(dll, "glutBitmapString");
		FreeGLUT::fn_glutStrokeString               = (decltype(&glutStrokeString))::GetProcAddress(dll, "glutStrokeString");
		FreeGLUT::fn_glutWireRhombicDodecahedron    = (decltype(&glutWireRhombicDodecahedron))::GetProcAddress(dll, "glutWireRhombicDodecahedron");
		FreeGLUT::fn_glutSolidRhombicDodecahedron   = (decltype(&glutSolidRhombicDodecahedron))::GetProcAddress(dll, "glutSolidRhombicDodecahedron");
		FreeGLUT::fn_glutWireSierpinskiSponge       = (decltype(&glutWireSierpinskiSponge ))::GetProcAddress(dll, "glutWireSierpinskiSponge ");
		FreeGLUT::fn_glutSolidSierpinskiSponge      = (decltype(&glutSolidSierpinskiSponge ))::GetProcAddress(dll, "glutSolidSierpinskiSponge ");
		FreeGLUT::fn_glutWireCylinder               = (decltype(&glutWireCylinder))::GetProcAddress(dll, "glutWireCylinder");
		FreeGLUT::fn_glutSolidCylinder              = (decltype(&glutSolidCylinder))::GetProcAddress(dll, "glutSolidCylinder");
		FreeGLUT::fn_glutWireTeacup                 = (decltype(&glutWireTeacup))::GetProcAddress(dll, "glutWireTeacup");
		FreeGLUT::fn_glutSolidTeacup                = (decltype(&glutSolidTeacup))::GetProcAddress(dll, "glutSolidTeacup");
		FreeGLUT::fn_glutWireTeaspoon               = (decltype(&glutWireTeaspoon))::GetProcAddress(dll, "glutWireTeaspoon");
		FreeGLUT::fn_glutSolidTeaspoon              = (decltype(&glutSolidTeaspoon))::GetProcAddress(dll, "glutSolidTeaspoon");
		FreeGLUT::fn_glutGetProcAddress             = (decltype(&glutGetProcAddress))::GetProcAddress(dll, "glutGetProcAddress");
		FreeGLUT::fn_glutMultiEntryFunc             = (decltype(&glutMultiEntryFunc))::GetProcAddress(dll, "glutMultiEntryFunc");
		FreeGLUT::fn_glutMultiButtonFunc            = (decltype(&glutMultiButtonFunc))::GetProcAddress(dll, "glutMultiButtonFunc");
		FreeGLUT::fn_glutMultiMotionFunc            = (decltype(&glutMultiMotionFunc))::GetProcAddress(dll, "glutMultiMotionFunc");
		FreeGLUT::fn_glutMultiPassiveFunc           = (decltype(&glutMultiPassiveFunc))::GetProcAddress(dll, "glutMultiPassiveFunc");
		FreeGLUT::fn_glutInitContextVersion         = (decltype(&glutInitContextVersion))::GetProcAddress(dll, "glutInitContextVersion");
		FreeGLUT::fn_glutInitContextFlags           = (decltype(&glutInitContextFlags))::GetProcAddress(dll, "glutInitContextFlags");
		FreeGLUT::fn_glutInitContextProfile         = (decltype(&glutInitContextProfile))::GetProcAddress(dll, "glutInitContextProfile");
		FreeGLUT::fn_glutInitErrorFunc              = (decltype(&glutInitErrorFunc))::GetProcAddress(dll, "glutInitErrorFunc");
		FreeGLUT::fn_glutInitWarningFunc            = (decltype(&glutInitWarningFunc))::GetProcAddress(dll, "glutInitWarningFunc");
		FreeGLUT::fn_glutSetVertexAttribCoord3      = (decltype(&glutSetVertexAttribCoord3))::GetProcAddress(dll, "glutSetVertexAttribCoord3");
		FreeGLUT::fn_glutSetVertexAttribNormal      = (decltype(&glutSetVertexAttribNormal))::GetProcAddress(dll, "glutSetVertexAttribNormal");
		FreeGLUT::fn_glutSetVertexAttribTexCoord2   = (decltype(&glutSetVertexAttribTexCoord2))::GetProcAddress(dll, "glutSetVertexAttribTexCoord2");
		FreeGLUT::fn_glutInitContextFunc            = (decltype(&glutInitContextFunc))::GetProcAddress(dll, "glutInitContextFunc");
		FreeGLUT::fn_glutAppStatusFunc              = (decltype(&glutAppStatusFunc))::GetProcAddress(dll, "glutAppStatusFunc");
	}

	PFN_glutInit                       fn_glutInit;
	PFN_glutInitWindowPosition         fn_glutInitWindowPosition;
	PFN_glutInitWindowSize             fn_glutInitWindowSize;
	PFN_glutInitDisplayMode            fn_glutInitDisplayMode;
	PFN_glutInitDisplayString          fn_glutInitDisplayString;
	PFN_glutMainLoop                   fn_glutMainLoop;
	PFN_glutCreateWindow               fn_glutCreateWindow;
	PFN_glutCreateSubWindow            fn_glutCreateSubWindow;
	PFN_glutDestroyWindow              fn_glutDestroyWindow;
	PFN_glutSetWindow                  fn_glutSetWindow;
	PFN_glutGetWindow                  fn_glutGetWindow;
	PFN_glutSetWindowTitle             fn_glutSetWindowTitle;
	PFN_glutSetIconTitle               fn_glutSetIconTitle;
	PFN_glutReshapeWindow              fn_glutReshapeWindow;
	PFN_glutPositionWindow             fn_glutPositionWindow;
	PFN_glutShowWindow                 fn_glutShowWindow;
	PFN_glutHideWindow                 fn_glutHideWindow;
	PFN_glutIconifyWindow              fn_glutIconifyWindow;
	PFN_glutPushWindow                 fn_glutPushWindow;
	PFN_glutPopWindow                  fn_glutPopWindow;
	PFN_glutFullScreen                 fn_glutFullScreen;
	PFN_glutPostWindowRedisplay        fn_glutPostWindowRedisplay;
	PFN_glutPostRedisplay              fn_glutPostRedisplay;
	PFN_glutSwapBuffers                fn_glutSwapBuffers;
	PFN_glutWarpPointer                fn_glutWarpPointer;
	PFN_glutSetCursor                  fn_glutSetCursor;
	PFN_glutEstablishOverlay           fn_glutEstablishOverlay;
	PFN_glutRemoveOverlay              fn_glutRemoveOverlay;
	PFN_glutUseLayer                   fn_glutUseLayer;
	PFN_glutPostOverlayRedisplay       fn_glutPostOverlayRedisplay;
	PFN_glutPostWindowOverlayRedisplay fn_glutPostWindowOverlayRedisplay;
	PFN_glutShowOverlay                fn_glutShowOverlay;
	PFN_glutHideOverlay                fn_glutHideOverlay;
	PFN_glutCreateMenu                 fn_glutCreateMenu;
	PFN_glutDestroyMenu                fn_glutDestroyMenu;
	PFN_glutGetMenu                    fn_glutGetMenu;
	PFN_glutSetMenu                    fn_glutSetMenu;
	PFN_glutAddMenuEntry               fn_glutAddMenuEntry;
	PFN_glutAddSubMenu                 fn_glutAddSubMenu;
	PFN_glutChangeToMenuEntry          fn_glutChangeToMenuEntry;
	PFN_glutChangeToSubMenu            fn_glutChangeToSubMenu;
	PFN_glutRemoveMenuItem             fn_glutRemoveMenuItem;
	PFN_glutAttachMenu                 fn_glutAttachMenu;
	PFN_glutDetachMenu                 fn_glutDetachMenu;
	PFN_glutTimerFunc                  fn_glutTimerFunc;
	PFN_glutIdleFunc                   fn_glutIdleFunc;
	PFN_glutKeyboardFunc               fn_glutKeyboardFunc;
	PFN_glutSpecialFunc                fn_glutSpecialFunc;
	PFN_glutReshapeFunc                fn_glutReshapeFunc;
	PFN_glutVisibilityFunc             fn_glutVisibilityFunc;
	PFN_glutDisplayFunc                fn_glutDisplayFunc;
	PFN_glutMouseFunc                  fn_glutMouseFunc;
	PFN_glutMotionFunc                 fn_glutMotionFunc;
	PFN_glutPassiveMotionFunc          fn_glutPassiveMotionFunc;
	PFN_glutEntryFunc                  fn_glutEntryFunc;
	PFN_glutKeyboardUpFunc             fn_glutKeyboardUpFunc;
	PFN_glutSpecialUpFunc              fn_glutSpecialUpFunc;
	PFN_glutJoystickFunc               fn_glutJoystickFunc;
	PFN_glutMenuStateFunc              fn_glutMenuStateFunc;
	PFN_glutMenuStatusFunc             fn_glutMenuStatusFunc;
	PFN_glutOverlayDisplayFunc         fn_glutOverlayDisplayFunc;
	PFN_glutWindowStatusFunc           fn_glutWindowStatusFunc;
	PFN_glutSpaceballMotionFunc        fn_glutSpaceballMotionFunc;
	PFN_glutSpaceballRotateFunc        fn_glutSpaceballRotateFunc;
	PFN_glutSpaceballButtonFunc        fn_glutSpaceballButtonFunc;
	PFN_glutButtonBoxFunc              fn_glutButtonBoxFunc;
	PFN_glutDialsFunc                  fn_glutDialsFunc;
	PFN_glutTabletMotionFunc           fn_glutTabletMotionFunc;
	PFN_glutTabletButtonFunc           fn_glutTabletButtonFunc;
	PFN_glutGet                        fn_glutGet;
	PFN_glutDeviceGet                  fn_glutDeviceGet;
	PFN_glutGetModifiers               fn_glutGetModifiers;
	PFN_glutLayerGet                   fn_glutLayerGet;
	PFN_glutBitmapCharacter            fn_glutBitmapCharacter;
	PFN_glutBitmapWidth                fn_glutBitmapWidth;
	PFN_glutStrokeCharacter            fn_glutStrokeCharacter;
	PFN_glutStrokeWidth                fn_glutStrokeWidth;
	PFN_glutStrokeWidthf               fn_glutStrokeWidthf;
	PFN_glutBitmapLength               fn_glutBitmapLength;
	PFN_glutStrokeLength               fn_glutStrokeLength;
	PFN_glutStrokeLengthf              fn_glutStrokeLengthf;
	PFN_glutWireCube                   fn_glutWireCube;
	PFN_glutSolidCube                  fn_glutSolidCube;
	PFN_glutWireSphere                 fn_glutWireSphere;
	PFN_glutSolidSphere                fn_glutSolidSphere;
	PFN_glutWireCone                   fn_glutWireCone;
	PFN_glutSolidCone                  fn_glutSolidCone;
	PFN_glutWireTorus                  fn_glutWireTorus;
	PFN_glutSolidTorus                 fn_glutSolidTorus;
	PFN_glutWireDodecahedron           fn_glutWireDodecahedron;
	PFN_glutSolidDodecahedron          fn_glutSolidDodecahedron;
	PFN_glutWireOctahedron             fn_glutWireOctahedron;
	PFN_glutSolidOctahedron            fn_glutSolidOctahedron;
	PFN_glutWireTetrahedron            fn_glutWireTetrahedron;
	PFN_glutSolidTetrahedron           fn_glutSolidTetrahedron;
	PFN_glutWireIcosahedron            fn_glutWireIcosahedron;
	PFN_glutSolidIcosahedron           fn_glutSolidIcosahedron;
	PFN_glutWireTeapot                 fn_glutWireTeapot;
	PFN_glutSolidTeapot                fn_glutSolidTeapot;
	PFN_glutGameModeString             fn_glutGameModeString;
	PFN_glutEnterGameMode              fn_glutEnterGameMode;
	PFN_glutLeaveGameMode              fn_glutLeaveGameMode;
	PFN_glutGameModeGet                fn_glutGameModeGet;
	PFN_glutVideoResizeGet             fn_glutVideoResizeGet;
	PFN_glutSetupVideoResizing         fn_glutSetupVideoResizing;
	PFN_glutStopVideoResizing          fn_glutStopVideoResizing;
	PFN_glutVideoResize                fn_glutVideoResize;
	PFN_glutVideoPan                   fn_glutVideoPan;
	PFN_glutSetColor                   fn_glutSetColor;
	PFN_glutGetColor                   fn_glutGetColor;
	PFN_glutCopyColormap               fn_glutCopyColormap;
	PFN_glutIgnoreKeyRepeat            fn_glutIgnoreKeyRepeat;
	PFN_glutSetKeyRepeat               fn_glutSetKeyRepeat;
	PFN_glutForceJoystickFunc          fn_glutForceJoystickFunc;
	PFN_glutExtensionSupported         fn_glutExtensionSupported;
	PFN_glutReportErrors               fn_glutReportErrors;
	PFN_glutMainLoopEvent              fn_glutMainLoopEvent;
	PFN_glutLeaveMainLoop              fn_glutLeaveMainLoop;
	PFN_glutExit                       fn_glutExit;
	PFN_glutFullScreenToggle           fn_glutFullScreenToggle;
	PFN_glutLeaveFullScreen            fn_glutLeaveFullScreen;
	PFN_glutSetMenuFont                fn_glutSetMenuFont;
	PFN_glutMouseWheelFunc             fn_glutMouseWheelFunc;
	PFN_glutPositionFunc               fn_glutPositionFunc;
	PFN_glutCloseFunc                  fn_glutCloseFunc;
	PFN_glutWMCloseFunc                fn_glutWMCloseFunc;
	PFN_glutMenuDestroyFunc            fn_glutMenuDestroyFunc;
	PFN_glutSetOption                  fn_glutSetOption;
	PFN_glutGetModeValues              fn_glutGetModeValues;
	PFN_glutGetWindowData              fn_glutGetWindowData;
	PFN_glutSetWindowData              fn_glutSetWindowData;
	PFN_glutGetMenuData                fn_glutGetMenuData;
	PFN_glutSetMenuData                fn_glutSetMenuData;
	PFN_glutBitmapHeight               fn_glutBitmapHeight;
	PFN_glutStrokeHeight               fn_glutStrokeHeight;
	PFN_glutBitmapString               fn_glutBitmapString;
	PFN_glutStrokeString               fn_glutStrokeString;
	PFN_glutWireRhombicDodecahedron    fn_glutWireRhombicDodecahedron;
	PFN_glutSolidRhombicDodecahedron   fn_glutSolidRhombicDodecahedron;
	PFN_glutWireSierpinskiSponge       fn_glutWireSierpinskiSponge;
	PFN_glutSolidSierpinskiSponge      fn_glutSolidSierpinskiSponge;
	PFN_glutWireCylinder               fn_glutWireCylinder;
	PFN_glutSolidCylinder              fn_glutSolidCylinder;
	PFN_glutWireTeacup                 fn_glutWireTeacup;
	PFN_glutSolidTeacup                fn_glutSolidTeacup;
	PFN_glutWireTeaspoon               fn_glutWireTeaspoon;
	PFN_glutSolidTeaspoon              fn_glutSolidTeaspoon;
	PFN_glutGetProcAddress             fn_glutGetProcAddress;
	PFN_glutMultiEntryFunc             fn_glutMultiEntryFunc;
	PFN_glutMultiButtonFunc            fn_glutMultiButtonFunc;
	PFN_glutMultiMotionFunc            fn_glutMultiMotionFunc;
	PFN_glutMultiPassiveFunc           fn_glutMultiPassiveFunc;
	PFN_glutInitContextVersion         fn_glutInitContextVersion;
	PFN_glutInitContextFlags           fn_glutInitContextFlags;
	PFN_glutInitContextProfile         fn_glutInitContextProfile;
	PFN_glutInitErrorFunc              fn_glutInitErrorFunc;
	PFN_glutInitWarningFunc            fn_glutInitWarningFunc;
	PFN_glutSetVertexAttribCoord3      fn_glutSetVertexAttribCoord3;
	PFN_glutSetVertexAttribNormal      fn_glutSetVertexAttribNormal;
	PFN_glutSetVertexAttribTexCoord2   fn_glutSetVertexAttribTexCoord2;
	PFN_glutInitContextFunc            fn_glutInitContextFunc;
	PFN_glutAppStatusFunc              fn_glutAppStatusFunc;

}
